#!/usr/bin/env python3
"""cluster_builder.py — Build explicit ion–water clusters for the cluster-continuum approach.

The cluster-continuum thermodynamic cycle (Pliego & Riveros 2001, Kelly et al. 2006)
improves absolute solvation free energies for ions by wrapping them with n explicit
water molecules before applying a continuum solvation model:

  Ion(g) + n·H₂O(g) → [Ion·(H₂O)_n](g)          ΔG°_bind   (DFT/gas)
  [Ion·(H₂O)_n](g)  → [Ion·(H₂O)_n](aq)          ΔG°_cont   (DFT/SMD)
  n·H₂O(l)          → n·H₂O(g)                    n·ΔG°_vap  (+6.32 kcal/mol each)

  ΔG°_solv(ion) = ΔG°_bind + ΔG°_cont − n·ΔG°_vap + ΔG°_ss

Oxygen placement strategy — Thomson problem
-------------------------------------------
Water oxygens are placed at equal distance R from the ion and at the maximum
mutual separation solving the Thomson problem: minimise the Coulomb energy

    E = Σ_{i<j} 1 / |r_i − r_j|

Exact solutions are used for n = 1–6; scipy.optimize handles larger n.
Conformers are generated by applying a random global rotation to the whole
optimised cluster, so inter-oxygen distances are always preserved.

Usage:
  python cluster_builder.py -f Na.xyz -c 1 -n 1 2 3 4 --nconformers 5
  python cluster_builder.py -f Cl.xyz -c -1 -n 4 6 --nconformers 5 --anion
  python cluster_builder.py -f Mg.xyz -c 2 -n 6   --ion-o-dist 2.05
"""

from __future__ import annotations

import argparse
import math
import sys
import textwrap
from pathlib import Path
from typing import List, Optional, Tuple

import numpy as np
from scipy.optimize import minimize

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from input_prep.generate_inputs import CalcConfig, GaussianInputGenerator, _sanitize

# ---------------------------------------------------------------------------
# Water molecule geometry  (r_OH = 0.9572 Å, HOH = 104.52°)
# Local frame: O at origin, HOH bisector along +z, molecule in xz plane.
# For cation solvation the bisector (+z) points AWAY from the ion, so the
# O lone pairs face the ion and H atoms point outward.
# ---------------------------------------------------------------------------

_HALF_HOH = math.radians(104.52 / 2)          # 52.26°
_R_OH = 0.9572                                 # Å

# H positions in local frame (bisector = +z)
_H_LOCAL = np.array([
    [ math.sin(_HALF_HOH) * _R_OH, 0.0,  math.cos(_HALF_HOH) * _R_OH],
    [-math.sin(_HALF_HOH) * _R_OH, 0.0,  math.cos(_HALF_HOH) * _R_OH],
])

# Default ion–O first-shell distances (Å)
DEFAULT_ION_O_DIST: dict[str, float] = {
    "Li": 1.95, "Na": 2.35, "K": 2.80, "Rb": 2.95, "Cs": 3.15,
    "Mg": 2.05, "Ca": 2.45, "Sr": 2.65, "Ba": 2.85,
    "F":  2.65, "Cl": 3.10, "Br": 3.30, "I":  3.55,
    "default": 2.50,
}


# ---------------------------------------------------------------------------
# Thomson problem: maximally-separated points on the unit sphere
# ---------------------------------------------------------------------------

# Exact solutions for n = 1–6
_THOMSON_EXACT: dict[int, np.ndarray] = {
    1: np.array([[0., 0., 1.]]),
    2: np.array([[0., 0., 1.], [0., 0., -1.]]),
    3: np.array([
        [1., 0., 0.],
        [-0.5,  math.sqrt(3)/2, 0.],
        [-0.5, -math.sqrt(3)/2, 0.],
    ]),
    4: np.array([           # tetrahedral
        [ 0.,               0.,              1.           ],
        [ 2*math.sqrt(2)/3, 0.,             -1/3          ],
        [-math.sqrt(2)/3,   math.sqrt(6)/3, -1/3          ],
        [-math.sqrt(2)/3,  -math.sqrt(6)/3, -1/3          ],
    ]),
    5: np.array([           # triangular bipyramid
        [ 0.,  0.,  1.],
        [ 0.,  0., -1.],
        [ 1.,  0.,  0.],
        [-0.5,  math.sqrt(3)/2, 0.],
        [-0.5, -math.sqrt(3)/2, 0.],
    ]),
    6: np.array([           # octahedral
        [ 1., 0., 0.], [-1., 0., 0.],
        [ 0., 1., 0.], [ 0.,-1., 0.],
        [ 0., 0., 1.], [ 0., 0.,-1.],
    ]),
}


def thomson_sphere(n: int, n_iter: int = 2000) -> np.ndarray:
    """Return n unit vectors maximally separated on the unit sphere.

    Uses exact solutions for n ≤ 6 and gradient-descent minimisation of
    the Coulomb energy for larger n.

    Returns
    -------
    directions : (n, 3) array of unit vectors
    """
    if n in _THOMSON_EXACT:
        vecs = _THOMSON_EXACT[n].copy()
        # normalise (exact entries are already unit but let's be safe)
        return vecs / np.linalg.norm(vecs, axis=1, keepdims=True)

    # ---- General case: minimise Coulomb energy on the sphere ----
    def _project(x):
        x = x.reshape(n, 3)
        return x / np.linalg.norm(x, axis=1, keepdims=True)

    def _objective(x_flat):
        pts = _project(x_flat)
        E, G = 0.0, np.zeros_like(pts)
        for i in range(n):
            d = pts[i] - pts          # (n, 3)
            r2 = np.einsum("ij,ij->i", d, d)
            r2[i] = 1.0               # avoid self
            r = np.sqrt(r2)
            inv_r = 1.0 / r
            inv_r[i] = 0.0
            E += 0.5 * inv_r.sum()
            inv_r3 = inv_r ** 3
            inv_r3[i] = 0.0
            G[i] = -(inv_r3[:, None] * d).sum(axis=0)
        return E, G.flatten()

    # Warm start: Fibonacci lattice projected onto sphere
    golden = (1 + math.sqrt(5)) / 2
    idx = np.arange(n)
    theta = np.arccos(1 - 2 * (idx + 0.5) / n)
    phi = 2 * math.pi * idx / golden
    x0 = np.column_stack([
        np.sin(theta) * np.cos(phi),
        np.sin(theta) * np.sin(phi),
        np.cos(theta),
    ]).flatten()

    res = minimize(_objective, x0, jac=True, method="L-BFGS-B",
                   options={"maxiter": n_iter, "ftol": 1e-12})
    return _project(res.x)


# ---------------------------------------------------------------------------
# Rotation helpers
# ---------------------------------------------------------------------------

def _rotation_to_align(source: np.ndarray, target: np.ndarray) -> np.ndarray:
    """3×3 rotation matrix that rotates unit vector `source` to `target`."""
    source = source / np.linalg.norm(source)
    target = target / np.linalg.norm(target)
    c = float(np.dot(source, target))
    if c > 1 - 1e-10:                    # already aligned
        return np.eye(3)
    if c < -1 + 1e-10:                   # antiparallel — 180° around any perp axis
        perp = (np.array([1., 0., 0.]) if abs(source[0]) < 0.9
                else np.array([0., 1., 0.]))
        v = np.cross(source, perp)
        v /= np.linalg.norm(v)
        return 2 * np.outer(v, v) - np.eye(3)
    v = np.cross(source, target)
    s = np.linalg.norm(v)
    kmat = np.array([[0, -v[2], v[1]],
                     [v[2], 0, -v[0]],
                     [-v[1], v[0], 0]])
    return np.eye(3) + kmat + kmat @ kmat * (1 - c) / (s * s)


def _rotation_around_axis(axis: np.ndarray, angle_rad: float) -> np.ndarray:
    """3×3 rotation matrix for `angle_rad` around unit `axis` (Rodrigues)."""
    axis = axis / np.linalg.norm(axis)
    c, s = math.cos(angle_rad), math.sin(angle_rad)
    x, y, z = axis
    return np.array([
        [c + x*x*(1-c),   x*y*(1-c) - z*s, x*z*(1-c) + y*s],
        [y*x*(1-c) + z*s, c + y*y*(1-c),   y*z*(1-c) - x*s],
        [z*x*(1-c) - y*s, z*y*(1-c) + x*s, c + z*z*(1-c)  ],
    ])


def _random_rotation(rng: np.random.Generator) -> np.ndarray:
    """Uniformly random rotation matrix via quaternion sampling."""
    q = rng.standard_normal(4)
    q /= np.linalg.norm(q)
    w, x, y, z = q
    return np.array([
        [1 - 2*(y*y + z*z),   2*(x*y - z*w),     2*(x*z + y*w)],
        [2*(x*y + z*w),       1 - 2*(x*x + z*z),  2*(y*z - x*w)],
        [2*(x*z - y*w),       2*(y*z + x*w),      1 - 2*(x*x + y*y)],
    ])


# ---------------------------------------------------------------------------
# Water placement
# ---------------------------------------------------------------------------

def _place_water(
    ion_pos: np.ndarray,
    direction: np.ndarray,
    ion_o_dist: float,
    dihedral_rad: float = 0.0,
    o_toward_ion: bool = True,
) -> List[Tuple[str, float, float, float]]:
    """Place one water molecule at `direction` from `ion_pos`.

    Parameters
    ----------
    direction    : unit vector from ion toward the O position
    ion_o_dist   : ion–O distance (Å)
    dihedral_rad : rotation of the water around the ion–O axis
    o_toward_ion : if True (cations) the O lone pairs face the ion and H atoms
                   point outward; if False (anions) one H points toward the ion
    """
    o_pos = ion_pos + direction * ion_o_dist

    if o_toward_ion:
        # bisector (+z in local frame) points along `direction` (away from ion)
        bisector_world = direction
    else:
        # bisector points TOWARD ion (−direction), H atoms face the ion
        bisector_world = -direction

    # Rotation: align local +z with bisector_world
    R_align = _rotation_to_align(np.array([0., 0., 1.]), bisector_world)

    # Additional dihedral spin around the ion–O axis
    R_dihedral = _rotation_around_axis(direction, dihedral_rad)

    R_total = R_dihedral @ R_align

    coords: List[Tuple[str, float, float, float]] = [
        ("O", float(o_pos[0]), float(o_pos[1]), float(o_pos[2]))
    ]
    for h_local in _H_LOCAL:
        h_world = o_pos + R_total @ h_local
        coords.append(("H", float(h_world[0]), float(h_world[1]), float(h_world[2])))
    return coords


# ---------------------------------------------------------------------------
# Cluster builder
# ---------------------------------------------------------------------------

def build_cluster(
    ion_coords: List[Tuple[str, float, float, float]],
    n_water: int,
    ion_o_dist: Optional[float] = None,
    seed: int = 0,
    o_toward_ion: bool = True,
) -> List[Tuple[str, float, float, float]]:
    """Build one [ion·(H₂O)_n] cluster.

    Oxygen atoms are placed at the Thomson-optimal positions (maximum mutual
    separation on the sphere of radius `ion_o_dist`).  The conformer identity
    is encoded in `seed`, which drives a random global rotation of the cluster
    so that inter-oxygen distances are always Thomson-optimal.

    Parameters
    ----------
    ion_coords  : bare-ion coordinates
    n_water     : number of water molecules
    ion_o_dist  : ion–O distance in Å (auto-detected if None)
    seed        : random seed; seed=0 → canonical orientation, seed>0 → rotated
    o_toward_ion: True for cations (O lone pairs face ion), False for anions
    """
    rng = np.random.default_rng(seed)

    ion_center = np.mean([[x, y, z] for _, x, y, z in ion_coords], axis=0)

    if ion_o_dist is None:
        first_sym = ion_coords[0][0]
        ion_o_dist = DEFAULT_ION_O_DIST.get(first_sym, DEFAULT_ION_O_DIST["default"])

    # Optimal O directions on unit sphere
    directions = thomson_sphere(n_water)     # shape (n, 3)

    # Conformer: rotate the entire set of O directions by one global rotation
    if seed != 0:
        R_global = _random_rotation(rng)
        directions = (R_global @ directions.T).T

    cluster = list(ion_coords)
    for i, direction in enumerate(directions):
        # Each water gets a random dihedral spin around its ion–O axis
        dihedral = rng.uniform(0, 2 * math.pi)
        water = _place_water(ion_center, direction, ion_o_dist,
                             dihedral_rad=dihedral, o_toward_ion=o_toward_ion)
        cluster.extend(water)

    return cluster


# ---------------------------------------------------------------------------
# Geometry validation
# ---------------------------------------------------------------------------

def min_distance(coords: List[Tuple[str, float, float, float]]) -> Tuple[float, str]:
    """Return the minimum interatomic distance and the offending atom pair."""
    pts = np.array([[x, y, z] for _, x, y, z in coords])
    syms = [s for s, *_ in coords]
    n = len(pts)
    d_min = 1e9
    pair = ""
    for i in range(n):
        for j in range(i + 1, n):
            d = float(np.linalg.norm(pts[i] - pts[j]))
            if d < d_min:
                d_min = d
                pair = f"{syms[i]}({i})–{syms[j]}({j})"
    return d_min, pair


# ---------------------------------------------------------------------------
# XYZ I/O
# ---------------------------------------------------------------------------

def write_xyz(
    coords: List[Tuple[str, float, float, float]],
    path: Path,
    comment: str = "",
) -> None:
    lines = [str(len(coords)), comment]
    for sym, x, y, z in coords:
        lines.append(f"{sym:<3s}  {x:>14.8f}  {y:>14.8f}  {z:>14.8f}")
    path.write_text("\n".join(lines) + "\n")


def read_xyz(path: Path) -> List[Tuple[str, float, float, float]]:
    lines = path.read_text().splitlines()
    n = int(lines[0].strip())
    coords = []
    for line in lines[2 : 2 + n]:
        parts = line.split()
        coords.append((parts[0], float(parts[1]), float(parts[2]), float(parts[3])))
    return coords


# ---------------------------------------------------------------------------
# Batch generation
# ---------------------------------------------------------------------------

def _launch_viewer(xyz_paths: List[Path], charge: int, html_out: Path) -> None:
    """Save an HTML viewer for a list of XYZ files (non-Jupyter fallback)."""
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
        from utils.visualize import show_cluster_grid
        show_cluster_grid(xyz_paths, charge=charge, html_output=html_out)
    except Exception as exc:
        print(f"  [visualize] Could not generate viewer: {exc}")


def generate_clusters(
    ion_xyz: Path,
    charge: int,
    mult: int,
    n_water_list: List[int],
    n_conformers: int,
    config: CalcConfig,
    outdir: Path,
    ion_o_dist: Optional[float] = None,
    o_toward_ion: bool = True,
    visualize: bool = False,
) -> None:
    """Generate XYZ + Gaussian .com files for each (n_water, conformer) pair.

    Directory layout:
      outdir/
        <stem>_n<N>_conf<K>/
          <stem>_n<N>_conf<K>_cluster.xyz
          <stem>_n<N>_conf<K>_gas.com
          <stem>_n<N>_conf<K>_solv.com
    """
    ion_coords = read_xyz(ion_xyz)
    stem = _sanitize(ion_xyz.stem)
    gen = GaussianInputGenerator(config)
    orientation = "O→ion" if o_toward_ion else "H→ion"

    for n in n_water_list:
        print(f"\n  n={n} ({orientation}, Thomson-optimal O placement):")
        xyz_written: List[Path] = []

        for conf in range(n_conformers):
            label = f"{stem}_n{n}_conf{conf}"
            job_dir = outdir / label
            job_dir.mkdir(parents=True, exist_ok=True)

            cluster = build_cluster(
                ion_coords,
                n_water=n,
                ion_o_dist=ion_o_dist,
                seed=conf,
                o_toward_ion=o_toward_ion,
            )

            d_min, pair = min_distance(cluster)

            xyz_out = job_dir / f"{label}_cluster.xyz"
            write_xyz(cluster, xyz_out,
                      comment=f"{stem}+{n}H2O conf{conf} | d_min={d_min:.2f}A Thomson")
            xyz_written.append(xyz_out)

            gen.write_all(xyz_path=xyz_out, charge=charge, mult=mult,
                          outdir=job_dir, name=label)

            print(f"    conf{conf}: d_min={d_min:.2f} Å ({pair})  → {job_dir.name}/")

        if visualize and xyz_written:
            _launch_viewer(xyz_written, charge, outdir / f"{stem}_n{n}_viewer.html")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Build ion–water clusters with Thomson-optimal O placement.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              # Na+ (cation, O toward ion)
              python cluster_builder.py -f Na.xyz -c 1 -n 1 2 3 4 --nconformers 5

              # Cl- (anion, H toward ion)
              python cluster_builder.py -f Cl.xyz -c -1 -n 1 2 3 4 --anion

              # Override ion-O distance
              python cluster_builder.py -f Mg.xyz -c 2 -n 6 --ion-o-dist 2.05
        """),
    )
    p.add_argument("-f", "--file", required=True, metavar="XYZ")
    p.add_argument("-c", "--charge", type=int, required=True)
    p.add_argument("-m", "--mult", type=int, default=1)
    p.add_argument("-n", "--n-water", nargs="+", type=int, default=[1, 2, 3, 4], metavar="N")
    p.add_argument("--nconformers", type=int, default=5, metavar="K")
    p.add_argument("--anion", action="store_true",
                   help="Orient water with H toward ion (for anions)")
    p.add_argument("--ion-o-dist", type=float, default=None, metavar="Å")
    p.add_argument("--config", metavar="YAML")
    p.add_argument("--functional", default=None)
    p.add_argument("--basis", default=None)
    p.add_argument("--nproc", type=int, default=None)
    p.add_argument("--mem", default=None)
    p.add_argument("--solvent", default=None)
    p.add_argument("-o", "--outdir", default="cluster_inputs")
    p.add_argument(
        "--view", action="store_true",
        help=(
            "Generate an HTML viewer for each n after building clusters. "
            "In Jupyter: returns nglview widgets. "
            "In CLI: saves <stem>_n<N>_viewer.html (requires rdkit + nglview "
            "for Jupyter; only needs the built-in 3Dmol.js CDN for CLI HTML)."
        ),
    )
    return p.parse_args()


def main() -> None:
    args = _parse_args()

    cfg = CalcConfig.from_yaml(args.config) if args.config else CalcConfig()
    if args.functional: cfg.functional = args.functional
    if args.basis:      cfg.basis_set  = args.basis
    if args.nproc:      cfg.nproc      = args.nproc
    if args.mem:        cfg.mem        = args.mem
    if args.solvent:    cfg.solvent    = args.solvent

    ion_xyz = Path(args.file)
    if not ion_xyz.exists():
        raise FileNotFoundError(ion_xyz)

    outdir = Path(args.outdir)
    print(f"Building clusters: {ion_xyz.name}  n={args.n_water}  conformers={args.nconformers}")
    generate_clusters(
        ion_xyz=ion_xyz,
        charge=args.charge,
        mult=args.mult,
        n_water_list=args.n_water,
        n_conformers=args.nconformers,
        config=cfg,
        outdir=outdir,
        ion_o_dist=args.ion_o_dist,
        o_toward_ion=not args.anion,
        visualize=args.view,
    )
    print(f"\nDone → {outdir}/")


if __name__ == "__main__":
    main()
