#!/usr/bin/env python3
"""multi_shell_builder.py — Build multi-shell explicit water clusters for gas-phase DFT.

Strategy
--------
Convergence problems with the cluster-continuum (CC) model are avoided by
using a purely explicit solvent approach: all water molecules are included
explicitly and the calculation is run in gas phase (no SCRF/SMD).

Shell placement
~~~~~~~~~~~~~~~
Shell 1  (inner)  : Thomson-optimal O positions at radius R₁ from the ion.
                    O lone pairs face the cation (or H toward anion).
Shell 2+  (outer) : Each H of the previous shell is a H-bond donor.
                    The next shell's O is placed at distance d_HB along
                    the O–H bond direction, past the H:

                        inner_O ──── inner_H ··· outer_O
                                 R_OH            d_HB ≈ 1.80 Å

                    The outer water is oriented with its lone pairs toward
                    inner_H (i.e., it acts as H-bond acceptor).

                    If more waters are requested than available H-bond
                    sites (> 2 × n_prev), the excess is distributed via
                    Thomson on a sphere of radius R_prev + 2.76 Å.

Conformers
~~~~~~~~~~
Each conformer is generated by a single random global rotation of the
first shell, after which outer shells are recomputed from the new H
positions. This preserves Thomson geometry in shell 1 and H-bond
geometry in outer shells across all conformers.

Gas-phase only
~~~~~~~~~~~~~~
Only opt+freq gas-phase .com files are generated (no SCRF). The SCF
convergence difficulties associated with continuum models are therefore
avoided entirely.

Usage
-----
  # Na⁺ with 6-water inner shell + 12-water outer shell (18 waters total)
  python input_prep/multi_shell_builder.py \\
      -f examples/ions/Na.xyz -c 1 \\
      --shells 6 12 --nconformers 5 -o jobs/Na_explicit/

  # Three shells
  python input_prep/multi_shell_builder.py \\
      -f examples/ions/Na.xyz -c 1 \\
      --shells 6 12 18 --nconformers 3 -o jobs/Na_3shells/

  # Anion (H toward ion for shell 1)
  python input_prep/multi_shell_builder.py \\
      -f examples/ions/Cl.xyz -c -1 \\
      --shells 6 12 --anion --nconformers 5 -o jobs/Cl_explicit/
"""

from __future__ import annotations

import argparse
import math
import sys
import textwrap
from pathlib import Path
from typing import List, Optional, Tuple

import numpy as np
from scipy.optimize import minimize

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from input_prep.cluster_builder import (
    thomson_sphere,
    _rotation_to_align,
    _rotation_around_axis,
    _random_rotation,
    _H_LOCAL,
    _R_OH,
    DEFAULT_ION_O_DIST,
    write_xyz,
    read_xyz,
    min_distance,
)
from input_prep.generate_inputs import CalcConfig, GaussianInputGenerator, _sanitize

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# H-bond O···H distance (Å). The outer-shell O is placed this far past
# the inner-shell H, along the O–H bond direction.
D_HBOND = 1.80

# Typical O···O distance in liquid water H-bonds ≈ 2.76 Å
# (= R_OH 0.96 + D_HBOND 1.80)
D_OO_HBOND = _R_OH + D_HBOND   # ≈ 2.76 Å


# ---------------------------------------------------------------------------
# Water placement (shared with cluster_builder but reproduced here for clarity)
# ---------------------------------------------------------------------------

def _place_water(
    center_pos: np.ndarray,
    direction: np.ndarray,
    dist: float,
    dihedral_rad: float = 0.0,
    lone_pairs_toward_center: bool = True,
) -> List[Tuple[str, float, float, float]]:
    """Place one water molecule.

    The O is at `center_pos + direction * dist`.
    If `lone_pairs_toward_center` is True (default), the HOH bisector points
    away from center_pos (H atoms outward, lone pairs inward) — correct for
    both cation first-shell and H-bond acceptor geometry.
    """
    o_pos = center_pos + direction * dist
    bisector = direction if lone_pairs_toward_center else -direction

    R_align = _rotation_to_align(np.array([0.0, 0.0, 1.0]), bisector)
    R_dih = _rotation_around_axis(direction, dihedral_rad)
    R = R_dih @ R_align

    coords: List[Tuple[str, float, float, float]] = [
        ("O", float(o_pos[0]), float(o_pos[1]), float(o_pos[2]))
    ]
    for h_local in _H_LOCAL:
        hw = o_pos + R @ h_local
        coords.append(("H", float(hw[0]), float(hw[1]), float(hw[2])))
    return coords


# ---------------------------------------------------------------------------
# Dihedral optimisation: avoid H–H clashes
# ---------------------------------------------------------------------------

def _best_dihedral(
    o_pos: np.ndarray,
    direction: np.ndarray,
    existing_h_pos: List[np.ndarray],
    n_samples: int = 18,
) -> float:
    """Return the dihedral angle (rotation around `direction`) that places
    this water's H atoms furthest from all existing H atom positions.

    Samples `n_samples` evenly-spaced angles and picks the best.
    """
    if not existing_h_pos:
        return 0.0

    R_align = _rotation_to_align(np.array([0.0, 0.0, 1.0]), direction)
    existing = np.array(existing_h_pos)

    best_angle = 0.0
    best_min_d = -1.0

    for k in range(n_samples):
        angle = k * 2 * math.pi / n_samples
        R_dih = _rotation_around_axis(direction, angle)
        R = R_dih @ R_align
        h_world = [o_pos + R @ hl for hl in _H_LOCAL]
        # minimum distance from any of this water's H to any existing H
        min_d = min(
            float(np.linalg.norm(hw - eh))
            for hw in h_world
            for eh in existing
        )
        if min_d > best_min_d:
            best_min_d = min_d
            best_angle = angle

    return best_angle


# ---------------------------------------------------------------------------
# H-bond site extraction
# ---------------------------------------------------------------------------

def _hbond_acceptor_sites(
    shell_waters: List[Tuple[str, float, float, float]],
) -> List[Tuple[np.ndarray, np.ndarray]]:
    """Return H-bond acceptor site data for each H in a water shell.

    For each H atom of each water molecule, returns:
        (inner_h_pos, oh_unit_dir)
    where oh_unit_dir is the unit vector from O toward H (pointing outward).

    The outer-shell O should be placed at:
        inner_h_pos + D_HBOND * oh_unit_dir
    """
    sites = []
    n_waters = len(shell_waters) // 3
    for w in range(n_waters):
        _, xo, yo, zo = shell_waters[w * 3]
        o_pos = np.array([xo, yo, zo])
        for h_idx in (w * 3 + 1, w * 3 + 2):
            _, xh, yh, zh = shell_waters[h_idx]
            h_pos = np.array([xh, yh, zh])
            oh_dir = h_pos - o_pos
            oh_dir /= np.linalg.norm(oh_dir)
            sites.append((h_pos, oh_dir))
    return sites


# ---------------------------------------------------------------------------
# Multi-shell cluster builder
# ---------------------------------------------------------------------------

def build_multi_shell_cluster(
    ion_coords: List[Tuple[str, float, float, float]],
    n_per_shell: List[int],
    ion_o_dist: Optional[float] = None,
    seed: int = 0,
    o_toward_ion: bool = True,
) -> List[Tuple[str, float, float, float]]:
    """Build a multi-shell explicit water cluster.

    Parameters
    ----------
    ion_coords  : bare-ion coordinates
    n_per_shell : number of water molecules per shell, e.g. [6, 12] or [6, 12, 18]
    ion_o_dist  : ion–O distance for shell 1 (Å); auto-detected if None
    seed        : random seed; seed=0 → canonical, seed>0 → random global rotation
    o_toward_ion: True for cations (O lone pairs face ion), False for anions

    Returns
    -------
    Full cluster coordinates: ion + all shells as (symbol, x, y, z) list.
    """
    rng = np.random.default_rng(seed)

    ion_center = np.mean([[x, y, z] for _, x, y, z in ion_coords], axis=0)

    if ion_o_dist is None:
        first_sym = ion_coords[0][0]
        ion_o_dist = DEFAULT_ION_O_DIST.get(first_sym, DEFAULT_ION_O_DIST["default"])

    # ── Shell 1: Thomson-optimal around the ion ──────────────────────────
    n1 = n_per_shell[0]
    directions_s1 = thomson_sphere(n1)

    # Conformer: apply a single global rotation to shell 1
    if seed != 0:
        R_global = _random_rotation(rng)
        directions_s1 = (R_global @ directions_s1.T).T

    shell1_waters: List[Tuple[str, float, float, float]] = []
    placed_h: List[np.ndarray] = []   # accumulates all H positions placed so far

    for direction in directions_s1:
        o_pos = ion_center + direction * ion_o_dist
        dihedral = _best_dihedral(o_pos, direction, placed_h)
        water = _place_water(
            ion_center, direction, ion_o_dist,
            dihedral_rad=dihedral,
            lone_pairs_toward_center=o_toward_ion,
        )
        shell1_waters.extend(water)
        # Register the two H positions (indices 1 and 2 of the water tuple list)
        placed_h.append(np.array(water[1][1:]))
        placed_h.append(np.array(water[2][1:]))

    all_shells: List[List[Tuple[str, float, float, float]]] = [shell1_waters]

    # ── Outer shells: H-bond positions from previous shell ───────────────
    for shell_idx, n_shell in enumerate(n_per_shell[1:], start=2):
        prev_shell = all_shells[-1]
        hbond_sites = _hbond_acceptor_sites(prev_shell)  # up to 2 × n_prev sites
        n_hbond = len(hbond_sites)

        shell_waters: List[Tuple[str, float, float, float]] = []

        # ── Part A: fill H-bond sites (up to min(n_shell, n_hbond)) ──────
        n_from_hbond = min(n_shell, n_hbond)

        # If n_shell < n_hbond, pick the sites most evenly spread
        if n_from_hbond < n_hbond:
            step = n_hbond / n_from_hbond
            selected = [hbond_sites[round(i * step) % n_hbond]
                        for i in range(n_from_hbond)]
        else:
            selected = hbond_sites

        for h_pos, oh_dir in selected:
            o_pos = h_pos + D_HBOND * oh_dir
            dihedral = _best_dihedral(o_pos, oh_dir, placed_h)
            water = _place_water(
                h_pos, oh_dir, D_HBOND,
                dihedral_rad=dihedral,
                lone_pairs_toward_center=True,
            )
            shell_waters.extend(water)
            placed_h.append(np.array(water[1][1:]))
            placed_h.append(np.array(water[2][1:]))

        # ── Part B: Thomson fill if n_shell > n_hbond ────────────────────
        n_extra = n_shell - n_from_hbond
        if n_extra > 0:
            prev_o_positions = np.array([
                [x, y, z] for sym, x, y, z in prev_shell if sym == "O"
            ])
            r_prev = float(np.mean(np.linalg.norm(
                prev_o_positions - ion_center, axis=1
            )))
            r_fill = r_prev + D_OO_HBOND

            extra_dirs = thomson_sphere(n_extra)
            if seed != 0:
                R_extra = _random_rotation(rng)
                extra_dirs = (R_extra @ extra_dirs.T).T

            for direction in extra_dirs:
                o_pos = ion_center + direction * r_fill
                dihedral = _best_dihedral(o_pos, direction, placed_h)
                water = _place_water(
                    ion_center, direction, r_fill,
                    dihedral_rad=dihedral,
                    lone_pairs_toward_center=True,
                )
                shell_waters.extend(water)
                placed_h.append(np.array(water[1][1:]))
                placed_h.append(np.array(water[2][1:]))

        all_shells.append(shell_waters)

    # ── Assemble full cluster ─────────────────────────────────────────────
    cluster = list(ion_coords)
    for shell in all_shells:
        cluster.extend(shell)
    return cluster


# ---------------------------------------------------------------------------
# Summary statistics
# ---------------------------------------------------------------------------

def cluster_summary(
    coords: List[Tuple[str, float, float, float]],
    n_per_shell: List[int],
    ion_center: np.ndarray,
) -> str:
    """Return a human-readable summary of shell radii and minimum distances."""
    n_ion = len(coords) - sum(n_per_shell) * 3
    lines = []
    offset = n_ion
    for s, n in enumerate(n_per_shell, start=1):
        # Each water is stored as O, H, H (3 atoms). O is at index 0 of each triple.
        o_pos = np.array([
            [coords[offset + w * 3][1],
             coords[offset + w * 3][2],
             coords[offset + w * 3][3]]
            for w in range(n)
        ])
        radii = np.linalg.norm(o_pos - ion_center, axis=1)
        lines.append(
            f"  Shell {s}: {n:2d} H₂O | "
            f"R_O = {radii.mean():.2f} ± {radii.std():.2f} Å"
        )
        offset += n * 3

    d_min, pair = min_distance(coords)
    lines.append(f"  d_min (all atoms) = {d_min:.2f} Å  [{pair}]")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Batch generation
# ---------------------------------------------------------------------------

def generate_multi_shell_jobs(
    ion_xyz: Path,
    charge: int,
    mult: int,
    n_per_shell: List[int],
    n_conformers: int,
    config: CalcConfig,
    outdir: Path,
    ion_o_dist: Optional[float] = None,
    o_toward_ion: bool = True,
    visualize: bool = False,
) -> None:
    """Generate XYZ + gas-phase Gaussian .com files for multi-shell clusters.

    Only gas-phase opt+freq inputs are created (no SCRF). This avoids
    the SCF convergence issues associated with continuum solvation models
    on large cluster geometries.

    Directory layout:
      outdir/
        <stem>_s<shells>_conf<K>/
          <stem>_s<shells>_conf<K>_cluster.xyz
          <stem>_s<shells>_conf<K>_gas.com
    """
    ion_coords = read_xyz(ion_xyz)
    ion_center = np.mean([[x, y, z] for _, x, y, z in ion_coords], axis=0)
    stem = _sanitize(ion_xyz.stem)
    gen = GaussianInputGenerator(config)

    shell_label = "-".join(str(n) for n in n_per_shell)
    n_total = sum(n_per_shell)
    orientation = "O→ion" if o_toward_ion else "H→ion"

    print(f"\nShells: {n_per_shell}  ({n_total} waters total, {orientation})")
    print(f"Method: {config.functional}/{config.basis_set}  [gas phase only]")

    xyz_written: List[Path] = []

    for conf in range(n_conformers):
        label = f"{stem}_s{shell_label}_conf{conf}"
        job_dir = outdir / label
        job_dir.mkdir(parents=True, exist_ok=True)

        cluster = build_multi_shell_cluster(
            ion_coords,
            n_per_shell=n_per_shell,
            ion_o_dist=ion_o_dist,
            seed=conf,
            o_toward_ion=o_toward_ion,
        )

        summary = cluster_summary(cluster, n_per_shell, ion_center)
        xyz_out = job_dir / f"{label}_cluster.xyz"
        write_xyz(
            cluster, xyz_out,
            comment=f"{stem} {n_per_shell} H2O conf{conf} | gas-phase explicit",
        )
        xyz_written.append(xyz_out)

        # Gas-phase only — no SCRF
        gen.write_gas_opt_freq(
            xyz_path=xyz_out,
            charge=charge,
            mult=mult,
            outdir=job_dir,
            name=label,
        )

        d_min, pair = min_distance(cluster)
        print(f"\n  conf{conf}:")
        print(summary)

    if visualize and xyz_written:
        _launch_viewer(xyz_written, charge, outdir / f"{stem}_s{shell_label}_viewer.html")

    print(f"\nDone → {outdir}/  ({n_conformers} conformers × {n_total} waters = "
          f"{n_conformers * (1 + n_total * 3)} atoms/job)")


def _launch_viewer(xyz_paths: List[Path], charge: int, html_out: Path) -> None:
    try:
        from utils.visualize import show_cluster_grid
        show_cluster_grid(xyz_paths, charge=charge, html_output=html_out)
    except Exception as exc:
        print(f"  [visualize] {exc}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Build multi-shell explicit water clusters for gas-phase DFT.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              # Na⁺: 6 inner + 12 outer (18 waters total, gas phase)
              python input_prep/multi_shell_builder.py \\
                  -f examples/ions/Na.xyz -c 1 \\
                  --shells 6 12 --nconformers 5

              # Three shells
              python input_prep/multi_shell_builder.py \\
                  -f examples/ions/Na.xyz -c 1 \\
                  --shells 6 12 18 --nconformers 3

              # Cl⁻ (H toward ion in shell 1)
              python input_prep/multi_shell_builder.py \\
                  -f examples/ions/Cl.xyz -c -1 --anion \\
                  --shells 6 12 --nconformers 5

              # Compact test with visualisation
              python input_prep/multi_shell_builder.py \\
                  -f examples/ions/Na.xyz -c 1 \\
                  --shells 6 --nconformers 1 --view
        """),
    )
    p.add_argument("-f", "--file", required=True, metavar="XYZ")
    p.add_argument("-c", "--charge", type=int, required=True)
    p.add_argument("-m", "--mult", type=int, default=1)
    p.add_argument(
        "--shells", nargs="+", type=int, required=True, metavar="N",
        help="Number of water molecules per shell, e.g. --shells 6 12",
    )
    p.add_argument("--nconformers", type=int, default=5, metavar="K")
    p.add_argument(
        "--anion", action="store_true",
        help="Orient shell-1 waters with H toward ion (for anions)",
    )
    p.add_argument("--ion-o-dist", type=float, default=None, metavar="Å")
    p.add_argument("--config", metavar="YAML")
    p.add_argument("--functional", default=None)
    p.add_argument("--basis", default=None)
    p.add_argument("--nproc", type=int, default=None)
    p.add_argument("--mem", default=None)
    p.add_argument("-o", "--outdir", default="explicit_jobs")
    p.add_argument("--view", action="store_true", help="Save HTML viewer")
    return p.parse_args()


def main() -> None:
    args = _parse_args()

    cfg = CalcConfig.from_yaml(args.config) if args.config else CalcConfig()
    if args.functional: cfg.functional = args.functional
    if args.basis:      cfg.basis_set  = args.basis
    if args.nproc:      cfg.nproc      = args.nproc
    if args.mem:        cfg.mem        = args.mem

    ion_xyz = Path(args.file)
    if not ion_xyz.exists():
        raise FileNotFoundError(ion_xyz)

    generate_multi_shell_jobs(
        ion_xyz=ion_xyz,
        charge=args.charge,
        mult=args.mult,
        n_per_shell=args.shells,
        n_conformers=args.nconformers,
        config=cfg,
        outdir=Path(args.outdir),
        ion_o_dist=args.ion_o_dist,
        o_toward_ion=not args.anion,
        visualize=args.view,
    )


if __name__ == "__main__":
    main()
